# Generated by Django 5.0.7 on 2024-08-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
