# Generated by Django 5.0.8 on 2024-09-07 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="Candidate",
            new_name="candidate",
        ),
    ]
