# Generated by Django 5.0.8 on 2024-09-06 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='category',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='job_category',
            field=models.ManyToManyField(blank=True, to='app.jobcategory', verbose_name='job_category'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='job_category',
            field=models.ManyToManyField(blank=True, to='app.jobcategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='app.employer'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='experience',
            field=models.CharField(choices=[('0', 'Fresher'), ('1', '1 Year'), ('2', '2 Years'), ('3', '3 Years'), ('4', '4 Years'), ('5', '5 Years'), ('6', '6 Years')], default='Fresher', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='max_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='min_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='salary_type',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Weekly', 'Weekly'), ('Daily', 'Daily'), ('Hourly', 'Hourly'), ('Yearly', 'Yearly')], default='Monthly', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('filled', 'Filled'), ('draft', 'Draft')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='urgency_level',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Normal', 'Normal'), ('Immediate', 'Immediate')], max_length=10),
        ),
    ]
