# Generated by Django 5.0.7 on 2024-08-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_qualification_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location'),
        ),
    ]
