# Generated by Django 5.0.8 on 2024-09-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_candidate_contact_candidate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="application_deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
