# Generated by Django 5.0.8 on 2024-09-05 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_savedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.qualification', verbose_name='Qualification'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='founded_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
