# Generated by Django 5.0.8 on 2024-09-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_jobposting_application_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employer",
            name="founded_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
