# Generated by Django 5.0.7 on 2024-09-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='application_deadline',
            field=models.DateField(null=True),
        ),
    ]
