# Generated by Django 5.0.8 on 2024-09-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appliedjob'),
        ('app', '0003_remove_employer_location'),
    ]

    operations = [
    ]
