# Generated by Django 5.0.8 on 2024-09-11 09:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employer_saved_candidates_savedcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatemessage',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.candidate'),
        ),
        migrations.AddField(
            model_name='candidatemessage',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.employer'),
        ),
        migrations.AddField(
            model_name='candidatemessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidatemessage',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
